
cache_skims: True

spec_file_name: aggregate_od.csv

aggregate_od_matrices:
  skims_mfs: skims_mfs.omx
  skims_st: skims_st.omx
  skims_mt: skims_mt.omx
  mode_choice_pa_Lo: mode_choice_Lo.omx
  mode_choice_pa_Mi: mode_choice_Mi.omx
  mode_choice_pa_Hi: mode_choice_Hi.omx
  truck_trips: truck_mfs.omx
  # park_cost: parking_cost.omx

origin_zone_matrices:
  - ltpkg
  - stpkg

dest_zone_matrices:
  - ltpkg
  - stpkg


CONSTANTS:
  #value-of-time ($/hour; currently all equal, USDOT)
  #need to check 14.66 based on MACOG region average income, dollar of year
  VOT_HBO: 12.34
  VOT_HBS: 12.34
  VOT_HBW: 12.34
  VOT_NHBNW: 12.34
  VOT_NHBW: 12.34
  VOT_MEDTRK: 25.00
  VOT_HVYTRK: 38.00
  #Simple ITHIM
  POPULATION: 3000000
  WALK_SPEED: 3
  BIKE_SPEED: 10
  AVG_WALK_TIME_GROWTH_RATIO: -0.00028
  AVG_BIKE_TIME_GROWTH_RATIO: -0.00030
  DOLLARS_PER_DALY: 8000
  FIRST_EXTERNAL_ZONE: 927
