# values available to expressions in aggregate_demographics_processor
# CONSTANTS:
#   SAMPLE_CONSTANT: 42

#specify cocs
#note everybody is hard wired as 1.0 (100%)
#note * in the expressions means the expression applies to all cocs
coc_silos:
  - everybody
