
cache_skims: True

spec_file_name: aggregate_od.csv

aggregate_od_matrices:
  amskims: AM_skim.omx
  mdskims: MD_skim.omx
  pmskims: PM_skim.omx
  opskims: OP_skim.omx
  amtrips: AM_OD.omx
  mdtrips: MD_OD.omx
  pmtrips: PM_OD.omx
  optrips: OP_OD.omx


#origin_zone_matrices:
#  - ltpkg
#  - stpkg

#dest_zone_matrices:
#  - ltpkg
#  - stpkg


CONSTANTS:
  #value-of-time ($/hour; currently all equal, USDOT)
  #need to check 14.66 based on MACOG region average income, dollar of year
  VOT_AUTO: 12.63
  VOT_MUT: 55.10

